### PR TITLE
Added README.md and Makefile.

### PR DESCRIPTION
**Pull request by ypid**

### CODE REVIEW

**Comment by silvio** [comment]
I'm a little bit uncertain to have a Makefile for this. The only benefit what I see is that I have a configure string (`-e "TZ=Europe/Berlin"`) for remembering. Such settings should go in the startup system (systemd, upstart, initd) or you can use the `docker run` parameter `--restart=...`.

But, the `readme` file is great.

**Comment by ypid** [comment]
But I guess it does not hurt either? I think it is convenient to run `make build` to build the image locally. Another good use case of a Makefile is #12.

**Comment by silvio** [comment]
I have added a pull request about reorganisation of this repository (#17).

* Please put your makefile to the new `misc` folder
* Please change the now fixed `env` setting `-e ...` to a more flexible way or remove this setting.
* remove the comments in `build` target of the makefile.
* the `verify-gpg-public-keys` should print a text like `okay`/`not okay` or something like that

**Comment by ypid** [comment]
I not really agree with putting the Makefile in to the misc folder. It should be in the root of the repo. But ok. I moved it.

**Pull request merged**
