### PR TITLE
Increase upload size to 16G

### PR DESCRIPTION
**Pull request by egyptianbman**
Tracked down what owncloud uses to set the max upload size and implemented a 16G upload limit.

### CODE REVIEW

**Comment by ypid** [comment]
Thanks very much! Have you tested this and how big can the file be? Have you tried 16 GB?

**Comment by egyptianbman** [comment]
The latest commit updates everything else to allow up to 16G. I'm using an nginx proxy container and had to add the following custom configs:

```nginx
client_max_body_size  16G;
proxy_connect_timeout 21600;
proxy_send_timeout    21600;
proxy_read_timeout    21600;
send_timeout          21600;
```

I chose six hours for the timeout time because uploading 16G isn't exactly a zippy process.

**Comment by ypid** [comment]
All right. Merged, thx.

**Comment by ypid** [comment]
@egyptianbman Seems that this file is not expected to be changed.

```
occ integrity:check-core
  - INVALID_HASH:
    - .user.ini:
      - expected: 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
      - current: a923312c4f59ed57284843fdeae44658856634488513cf7d01d2e3f49c6dc6ab5ded5bc4649dde5186505f864ae86941e2a65e9d8a5965329921802b18322d3c
  - EXTRA_FILE:
    - .user.inie:
      - expected:
      - current: 6bdf1cf3bf08df0e82bdfca564a7d1e986f632a41417bcf63745be84c57721abaa03d0fb53ad236b910b0e99e602e5312d45ce3819feb470e98927bb4b1854f3
```

Can you rework your PR?

**Comment by ypid** [comment]
@egyptianbman I consider reverting your PR because of the above problem. Sorry for that. My main attention is on a different way to setup ownCloud via Ansible where you can also have a peek if you want. Ref: https://github.com/debops/ansible-owncloud/

**Comment by ypid** [comment]
@egyptianbman Hey, I just reverted this PR because `.user.ini` is not meant to be changed. Please rework this PR if you need it. Thanks anyway for your work!

**Pull request merged**
