### PR TITLE
Root path was wrong.

### PR DESCRIPTION
**Pull request by falaa**

### CODE REVIEW

**Comment by silvio** [comment]
Is this right that I doesn't need the "/owncloud" as urn start with this patch? If yes, than I have to change all my clients to the new url.

**Comment by silvio** [comment]
ping @jchaney :-)

**Comment by silvio** [comment]
Can you make this setting configurable?

**Comment by silvio** [comment]
@falaa Can you make this setting configurable?

**Comment by hourliert** [comment]
:+1:  That would be very usefull.

**Comment by silvio** [comment]
Hey @falaa, I have add a logic around your patch. Look at #21. You have to set `-e OWNCLOUD_IN_ROOTPATH=1` on start of owncloud.

**Pull request closed without merging**
