### PR TITLE
dockerfile: update to 8.0

### PR DESCRIPTION
**Pull request by silvio**
I have tested an update and seems to work. Please test carefully.

Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>

### CODE REVIEW

**Comment by silvio** [comment]
One thing: After an update, you have to reenable some apps...

**Comment by ypid** [comment]
I tested 8.0 with a Docker image based on [this commited](https://github.com/silvio/docker-owncloud/commit/35d0b917e29ba49da6c6072d12d4956b45e65a7c) (merged with the latest changes on master) and it works great (except maybe the reenabling of some apps as [mentioned](https://github.com/jchaney/owncloud/pull/10#issuecomment-76670596)).

**Comment by silvio** [comment]
Thx @ypid, @jchaney what do you thing about integration?

**Comment by ypid** [comment]
I updated two instances to 8.0.2. No compliance so far. The reenabling of apps is still there. I am not so familiar with owncloud, but maybe it is ok, when apps are stored in persistent storage?

**Comment by silvio** [comment]
I updated it to 8.0.2. Thx @ypid for pointing to 8.0.2 release.

@jchaney some reaction from your side?

**Comment by avelino** [comment]
For those using version 7 (and contains data), will update without problem?

**Comment by silvio** [comment]
I have used V7 before I had no problem on update.
But its **everytime** better to make a backup of you database/files before.

**Comment by avelino** [comment]
+1

**Comment by avelino** [comment]
Tested it and it worked perfectly for my files. In the same instance I keep my contacts, and it didn't work the contacts migration to version 8

**Comment by ypid** [comment]
You mean your contacts don’t show up after migrating? Did you reenable the contacts application? I myself did not test the migration from 7.x to 8. I started using ownCloud with version 8.

**Comment by leeychee** [comment]
I use this commit to build owncloud 8.0.2, but I got [this issue](https://github.com/owncloud/core/issues/14187).

**Comment by silvio** [comment]
@leeychee: I will prepare this patchset with a updated php installation.

**Comment by silvio** [comment]
@leeychee can you test this please. I had this issue not so I cannot test ^^

**Comment by ypid** [comment]
@jchaney Ping

In the meantime I merged all the latest patches into [my master branch](https://github.com/ypid/owncloud)..

**Comment by leeychee** [comment]
@silvio  So far(more than 2 weeks), it works fine.

**Comment by silvio** [comment]
@leeychee great! thx for testing!

**Comment by jchaney** [comment]
sorry I've been away from this project. Hoping I can actually turn it over to someone else who has more time. In the mean time, I've made @silvio a collaborator

**Comment by silvio** [comment]
ou okay. Thx @jchaney 
I will handle this and other issues at the/my evening(MET).

**Comment by silvio** [comment]
@jchaney is possible to make me a collaborator on the autobuild-docker repo <https://registry.hub.docker.com/u/jchaney/owncloud/> thing? I'm <https://hub.docker.com/u/silviof/>. TIA

**Comment by silvio** [comment]
@jchaney I step down from the collaborator role.

**Comment by ypid** [comment]
@jchaney I could take over. Still using/hosting it actively.

**Comment by jchaney** [comment]
@ypid awesome. I would be happy to completely turn it over to you, if that's possible. I have done so little since the initial commit, I don't really deserve ownership of it.

**Comment by jchaney** [comment]
@ypid would you like to take over the repo or just be a collaborator? also, do you have a docker hub username I can add you as a collaborator there. Not sure it will let me transfer that one though.

**Comment by ypid** [comment]
You can try it. My username is [ypid](https://hub.docker.com/u/ypid/).

**Comment by ypid** [comment]
Not sure about the collaborator vs. maintaining it under my account. I guess in the long run, it might make sense to migrate it to my account.

**Comment by jchaney** [comment]
@ypid it won't let me transfer it to you because you have a fork of it right now, but I've made you a collaborator in the mean time. Let me know if/when you want me to transfer it.

**Comment by ypid** [comment]
No problem. Thanks. Should be confident for the users of the image because it all stays the same.

**Comment by ypid** [comment]
@jchaney Not quite sure but it seems I don’t have full permissions on https://hub.docker.com/r/jchaney/owncloud yet to edit the description and to add Build Triggers. Can you edit this? Related to #45. It seems that Docker Hub currently does not allow to move Docker images to a different user so the decision about contributor vs. owner is still in favor to contributor to not break user updates. GitHub allows this but transferring ownership to me while Docker Hub does not allow this makes no sense.

**Comment by ypid** [comment]
@jchaney Can you recheck this on Docker Hub?

**Comment by jchaney** [comment]
@ypid it should be working. There is a dockerhub webhook set up on this repository connected to that dockerhub project. And dockerhub shows the github repositoy linked for automated builds.. it does show last push being 11 hours ago?

**Comment by ypid** [comment]
@jchaney Yes, Docker Hub triggers a build on repo push. But what I would like to do is to trigger an automatic build every night to include the latest security fixes even when there is no activity in this repository. See #45. The problem is that I don’t see the "Build settings" tab on https://hub.docker.com/r/jchaney/owncloud/~/settings/automated-builds which would allow me to define a "Build Triggers" which I could then call from cron. Alternatively could you enable a Build Trigger and send me the trigger URL?

**Comment by jchaney** [comment]
@ypid I sent you a private email with the details. Let me know if you need anything else.

**Comment by ypid** [comment]
@jchaney I did not yet receive your email. Can you resent to ypid@riseup.net ?

**Pull request merged**
