### PR TITLE
add cron support

### PR DESCRIPTION
**Pull request by silvio**
Signed-off-by: Silvio Fricke <silvio.fricke@gmail.com>

### CODE REVIEW

**Comment by silvio** [comment]
this commit fixes #1

**Comment by silvio** [comment]
rebased to new master

**Comment by jchaney** [comment]
docker.io just reported an automated build error to me:

`{"stream":"owncloud/apps/search_lucene/3`

I'm guessing cron broke something?

**Comment by silvio** [comment]
Is there a link for this message? I dont get this error at build time.

**Comment by jchaney** [comment]
https://registry.hub.docker.com/u/jchaney/owncloud/build_id/14024/code/bpzpsze2vm3nrwqm8muxuaz/

**Comment by silvio** [comment]
Hmm sorry but I got a "Sorry, you don't have access to this page."

**Pull request merged**
