### PR TITLE
Switch to Debian Jessie base image.

### LINKED ISSUE #13: Switch to Debian jessie base image?
Debian is the recommended base image for Docker. See https://docs.docker.com/articles/dockerfile_best-practices/#from

Any thoughts?

### PR DESCRIPTION
**Pull request by ypid**
Closes #13.

### CODE REVIEW

**Comment by silvio** [comment]
your patch reopen some issues which I have closed before. Please be carefully here.

**Comment by ypid** [comment]
Which onces?

**Comment by ypid** [comment]
If you are referring to the divert of `/sbin/initctl` check [`debootstrap`]](https://github.com/docker/docker/blob/c64466fb68c1ef204b8dc0759da62398a3372732/contrib/mkimage/debootstrap#L54) which handles this already.

**Comment by silvio** [comment]
Please read #10. And one other which I don't find now.
Please ensure that all changes are small as possible.

**Comment by ypid** [comment]
I am using three ownCloud instances based on Debian Jessie base images already and it works great.

**Comment by silvio** [comment]
The problem isn't the jessie-thing. 
I refer to the comment <https://github.com/jchaney/owncloud/pull/10#issuecomment-93213724>. So for now I will stay on ubuntu, and If I have time to test the jessie I will do this.

**Comment by silvio** [comment]
Okay - I have carefully reviewed and tested now. I was not aware that php5.6 is included in "debian:jessie".
So okay for this update. Please rebase ;-)

**Comment by ypid** [comment]
Done. You can also remove the divert. This does not have an effect for the Debian base image. I have been using my locally build owncloud image without the divert successfully.

**Pull request merged**
