### PR TITLE
Check downloaded archive with GPG.

### PR DESCRIPTION
**Pull request by ypid**
* This did not work for 7.0.4 so this commit also upgrades to Owncloud
  8.0.2. See #10 for dissuasion about v8.0.
* See also: https://github.com/patrickod/docker-tor/pull/8

### CODE REVIEW

**Comment by silvio** [comment]
Hi I have reviewed your patch.
Can you following thing change?

* please rebase
* download the <https://www.owncloud.org/owncloud.asc> file, and don't include it completly. It is possible that the gpg keys alter in the future.
* Introduce a version variable and use them for downloading of asc-file and archive.

**Comment by ypid** [comment]
Not including the signing key from ownCloud or at least specifying the fingerprint does destroy the whole purpose of checking the signature in the first place. What would happen when in the Dockerfile all three files are downloaded over https and someone hacks there website? Right, the attacker would create a new public/private key, sign the archive with it and upload the public key … When we remove the public key from this repo, there is no benefit in security …

I tried to verify the authenticate of the public key as good as I can and the commit which added the file is GPG signed with my public key.

Please reconsider …

**Comment by silvio** [comment]
Yeah okay. You are right. The altering of gpg keys should not happen frequently.

**Comment by ypid** [comment]
Not yet merged?

**Pull request closed without merging**
